# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # - image: node:8.11.3
      - image: circleci/node:jessie-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/project

    steps:
      - checkout
      - run: npm install
      - run: npm install -g grunt
      - run: npm install -g grunt-cli

      # run tests!
      - run: 
           name: "test command"
           command: grunt test --testParam="smokeTest"